export const products = [
  {
    id: 1,
    category: "cargos",
    product_name: "cargos_1.jpg",
    file_path: "men/bottom/cargos/cargos_1.jpg",
    price: 963,
    rating: 3.96,
  },
  {
    id: 2,
    category: "cargos",
    product_name: "cargos_10.jpg",
    file_path: "men/bottom/cargos/cargos_10.jpg",
    price: 560,
    rating: 4.06,
  },
  {
    id: 3,
    category: "cargos",
    product_name: "cargos_11.jpg",
    file_path: "men/bottom/cargos/cargos_11.jpg",
    price: 1381,
    rating: 4.06,
  },
  {
    id: 4,
    category: "cargos",
    product_name: "cargos_12.jpg",
    file_path: "men/bottom/cargos/cargos_12.jpg",
    price: 1197,
    rating: 3.48,
  },
  {
    id: 5,
    category: "cargos",
    product_name: "cargos_2.jpg",
    file_path: "men/bottom/cargos/cargos_2.jpg",
    price: 1314,
    rating: 4.65,
  },
  {
    id: 6,
    category: "cargos",
    product_name: "cargos_3.jpg",
    file_path: "men/bottom/cargos/cargos_3.jpg",
    price: 1858,
    rating: 3.89,
  },
  {
    id: 7,
    category: "cargos",
    product_name: "cargos_4.jpg",
    file_path: "men/bottom/cargos/cargos_4.jpg",
    price: 455,
    rating: 3.08,
  },
  {
    id: 8,
    category: "cargos",
    product_name: "cargos_5.jpg",
    file_path: "men/bottom/cargos/cargos_5.jpg",
    price: 1573,
    rating: 3.53,
  },
  {
    id: 9,
    category: "cargos",
    product_name: "cargos_6.jpg",
    file_path: "men/bottom/cargos/cargos_6.jpg",
    price: 1520,
    rating: 3.93,
  },
  {
    id: 10,
    category: "cargos",
    product_name: "cargos_7.jpg",
    file_path: "men/bottom/cargos/cargos_7.jpg",
    price: 1661,
    rating: 3.36,
  },
  {
    id: 11,
    category: "cargos",
    product_name: "cargos_8.jpg",
    file_path: "men/bottom/cargos/cargos_8.jpg",
    price: 526,
    rating: 4.38,
  },
  {
    id: 12,
    category: "cargos",
    product_name: "cargos_9.jpg",
    file_path: "men/bottom/cargos/cargos_9.jpg",
    price: 1434,
    rating: 4.35,
  },
  {
    id: 13,
    category: "jeans",
    product_name: "jeans_1.jpg",
    file_path: "men/bottom/jeans/jeans_1.jpg",
    price: 1708,
    rating: 4.91,
  },
  {
    id: 14,
    category: "jeans",
    product_name: "jeans_10.jpg",
    file_path: "men/bottom/jeans/jeans_10.jpg",
    price: 1714,
    rating: 4.46,
  },
  {
    id: 15,
    category: "jeans",
    product_name: "jeans_11.jpg",
    file_path: "men/bottom/jeans/jeans_11.jpg",
    price: 758,
    rating: 4.5,
  },
  {
    id: 16,
    category: "jeans",
    product_name: "jeans_12.jpg",
    file_path: "men/bottom/jeans/jeans_12.jpg",
    price: 1426,
    rating: 3.85,
  },
  {
    id: 17,
    category: "jeans",
    product_name: "jeans_2.jpg",
    file_path: "men/bottom/jeans/jeans_2.jpg",
    price: 1117,
    rating: 3.49,
  },
  {
    id: 18,
    category: "jeans",
    product_name: "jeans_3.jpg",
    file_path: "men/bottom/jeans/jeans_3.jpg",
    price: 1114,
    rating: 3.8,
  },
  {
    id: 19,
    category: "jeans",
    product_name: "jeans_4.jpg",
    file_path: "men/bottom/jeans/jeans_4.jpg",
    price: 491,
    rating: 3.72,
  },
  {
    id: 20,
    category: "jeans",
    product_name: "jeans_5.jpg",
    file_path: "men/bottom/jeans/jeans_5.jpg",
    price: 1413,
    rating: 4.2,
  },
  {
    id: 21,
    category: "jeans",
    product_name: "jeans_6.jpg",
    file_path: "men/bottom/jeans/jeans_6.jpg",
    price: 1833,
    rating: 4.5,
  },
  {
    id: 22,
    category: "jeans",
    product_name: "jeans_7.jpg",
    file_path: "men/bottom/jeans/jeans_7.jpg",
    price: 508,
    rating: 3.9,
  },
  {
    id: 23,
    category: "jeans",
    product_name: "jeans_8.jpg",
    file_path: "men/bottom/jeans/jeans_8.jpg",
    price: 1808,
    rating: 3.63,
  },
  {
    id: 24,
    category: "jeans",
    product_name: "jeans_9.jpg",
    file_path: "men/bottom/jeans/jeans_9.jpg",
    price: 328,
    rating: 4.82,
  },
  {
    id: 25,
    category: "casual",
    product_name: "casual_1.jpg",
    file_path: "men/top/casual/casual_1.jpg",
    price: 1062,
    rating: 4.41,
  },
  {
    id: 26,
    category: "casual",
    product_name: "casual_10.jpg",
    file_path: "men/top/casual/casual_10.jpg",
    price: 1131,
    rating: 3.97,
  },
  {
    id: 27,
    category: "casual",
    product_name: "casual_11.jpg",
    file_path: "men/top/casual/casual_11.jpg",
    price: 1388,
    rating: 4.08,
  },
  {
    id: 28,
    category: "casual",
    product_name: "casual_12.jpg",
    file_path: "men/top/casual/casual_12.jpg",
    price: 406,
    rating: 3.72,
  },
  {
    id: 29,
    category: "casual",
    product_name: "casual_2.jpg",
    file_path: "men/top/casual/casual_2.jpg",
    price: 750,
    rating: 3.26,
  },
  {
    id: 30,
    category: "casual",
    product_name: "casual_3.jpg",
    file_path: "men/top/casual/casual_3.jpg",
    price: 1524,
    rating: 3.69,
  },
  {
    id: 31,
    category: "casual",
    product_name: "casual_4.jpg",
    file_path: "men/top/casual/casual_4.jpg",
    price: 1404,
    rating: 3.91,
  },
  {
    id: 32,
    category: "casual",
    product_name: "casual_5.jpg",
    file_path: "men/top/casual/casual_5.jpg",
    price: 750,
    rating: 3.63,
  },
  {
    id: 33,
    category: "casual",
    product_name: "casual_6.jpg",
    file_path: "men/top/casual/casual_6.jpg",
    price: 820,
    rating: 3.24,
  },
  {
    id: 34,
    category: "casual",
    product_name: "casual_7.jpg",
    file_path: "men/top/casual/casual_7.jpg",
    price: 747,
    rating: 3.59,
  },
  {
    id: 35,
    category: "casual",
    product_name: "casual_8.jpg",
    file_path: "men/top/casual/casual_8.jpg",
    price: 1963,
    rating: 3.14,
  },
  {
    id: 36,
    category: "casual",
    product_name: "casual_9.jpg",
    file_path: "men/top/casual/casual_9.jpg",
    price: 913,
    rating: 3.65,
  },
  {
    id: 37,
    category: "formal",
    product_name: "formal_1.jpg",
    file_path: "men/top/formal/formal_1.jpg",
    price: 494,
    rating: 4.41,
  },
  {
    id: 38,
    category: "formal",
    product_name: "formal_10.jpg",
    file_path: "men/top/formal/formal_10.jpg",
    price: 742,
    rating: 3.59,
  },
  {
    id: 39,
    category: "formal",
    product_name: "formal_11.jpg",
    file_path: "men/top/formal/formal_11.jpg",
    price: 715,
    rating: 3.34,
  },
  {
    id: 40,
    category: "formal",
    product_name: "formal_12.jpg",
    file_path: "men/top/formal/formal_12.jpg",
    price: 602,
    rating: 4.33,
  },
  {
    id: 41,
    category: "formal",
    product_name: "formal_2.jpg",
    file_path: "men/top/formal/formal_2.jpg",
    price: 1797,
    rating: 3.24,
  },
  {
    id: 42,
    category: "formal",
    product_name: "formal_3.jpg",
    file_path: "men/top/formal/formal_3.jpg",
    price: 1915,
    rating: 4.53,
  },
  {
    id: 43,
    category: "formal",
    product_name: "formal_4.jpg",
    file_path: "men/top/formal/formal_4.jpg",
    price: 694,
    rating: 4.33,
  },
  {
    id: 44,
    category: "formal",
    product_name: "formal_5.jpg",
    file_path: "men/top/formal/formal_5.jpg",
    price: 864,
    rating: 3.64,
  },
  {
    id: 45,
    category: "formal",
    product_name: "formal_6.jpg",
    file_path: "men/top/formal/formal_6.jpg",
    price: 1018,
    rating: 3.28,
  },
  {
    id: 46,
    category: "formal",
    product_name: "formal_7.jpg",
    file_path: "men/top/formal/formal_7.jpg",
    price: 1959,
    rating: 4.02,
  },
  {
    id: 47,
    category: "formal",
    product_name: "formal_8.jpg",
    file_path: "men/top/formal/formal_8.jpg",
    price: 541,
    rating: 3.1,
  },
  {
    id: 48,
    category: "formal",
    product_name: "formal_9.jpg",
    file_path: "men/top/formal/formal_9.jpg",
    price: 1697,
    rating: 3.58,
  },
  {
    id: 49,
    category: "traditional",
    product_name: "traditional_1.jpg",
    file_path: "men/top/traditional/traditional_1.jpg",
    price: 1809,
    rating: 3.57,
  },
  {
    id: 50,
    category: "traditional",
    product_name: "traditional_10.jpg",
    file_path: "men/top/traditional/traditional_10.jpg",
    price: 1221,
    rating: 4.86,
  },
  {
    id: 51,
    category: "traditional",
    product_name: "traditional_11.jpg",
    file_path: "men/top/traditional/traditional_11.jpg",
    price: 1271,
    rating: 3.15,
  },
  {
    id: 52,
    category: "traditional",
    product_name: "traditional_12.jpg",
    file_path: "men/top/traditional/traditional_12.jpg",
    price: 835,
    rating: 4.42,
  },
  {
    id: 53,
    category: "traditional",
    product_name: "traditional_2.jpg",
    file_path: "men/top/traditional/traditional_2.jpg",
    price: 1840,
    rating: 4.2,
  },
  {
    id: 54,
    category: "traditional",
    product_name: "traditional_3.jpg",
    file_path: "men/top/traditional/traditional_3.jpg",
    price: 1049,
    rating: 3.95,
  },
  {
    id: 55,
    category: "traditional",
    product_name: "traditional_4.jpg",
    file_path: "men/top/traditional/traditional_4.jpg",
    price: 1714,
    rating: 3.36,
  },
  {
    id: 56,
    category: "traditional",
    product_name: "traditional_5.jpg",
    file_path: "men/top/traditional/traditional_5.jpg",
    price: 1601,
    rating: 3.64,
  },
  {
    id: 57,
    category: "traditional",
    product_name: "traditional_6.jpg",
    file_path: "men/top/traditional/traditional_6.jpg",
    price: 640,
    rating: 4.82,
  },
  {
    id: 58,
    category: "traditional",
    product_name: "traditional_7.jpg",
    file_path: "men/top/traditional/traditional_7.jpg",
    price: 528,
    rating: 3.29,
  },
  {
    id: 59,
    category: "traditional",
    product_name: "traditional_8.jpg",
    file_path: "men/top/traditional/traditional_8.jpg",
    price: 656,
    rating: 4.33,
  },
  {
    id: 60,
    category: "traditional",
    product_name: "traditional_9.jpg",
    file_path: "men/top/traditional/traditional_9.jpg",
    price: 1398,
    rating: 3.38,
  },
  {
    id: 61,
    category: "jeans",
    product_name: "jeans_1.jpg",
    file_path: "women/bottoms/jeans/jeans_1.jpg",
    price: 704,
    rating: 3.2,
  },
  {
    id: 62,
    category: "jeans",
    product_name: "jeans_10.jpg",
    file_path: "women/bottoms/jeans/jeans_10.jpg",
    price: 697,
    rating: 3.13,
  },
  {
    id: 63,
    category: "jeans",
    product_name: "jeans_11.jpg",
    file_path: "women/bottoms/jeans/jeans_11.jpg",
    price: 1848,
    rating: 3.31,
  },
  {
    id: 64,
    category: "jeans",
    product_name: "jeans_12.jpg",
    file_path: "women/bottoms/jeans/jeans_12.jpg",
    price: 1533,
    rating: 4.94,
  },
  {
    id: 65,
    category: "jeans",
    product_name: "jeans_2.jpg",
    file_path: "women/bottoms/jeans/jeans_2.jpg",
    price: 557,
    rating: 4.0,
  },
  {
    id: 66,
    category: "jeans",
    product_name: "jeans_3.jpg",
    file_path: "women/bottoms/jeans/jeans_3.jpg",
    price: 1976,
    rating: 3.94,
  },
  {
    id: 67,
    category: "jeans",
    product_name: "jeans_4.jpg",
    file_path: "women/bottoms/jeans/jeans_4.jpg",
    price: 1260,
    rating: 3.03,
  },
  {
    id: 68,
    category: "jeans",
    product_name: "jeans_5.jpg",
    file_path: "women/bottoms/jeans/jeans_5.jpg",
    price: 1706,
    rating: 4.45,
  },
  {
    id: 69,
    category: "jeans",
    product_name: "jeans_6.jpg",
    file_path: "women/bottoms/jeans/jeans_6.jpg",
    price: 1662,
    rating: 3.56,
  },
  {
    id: 70,
    category: "jeans",
    product_name: "jeans_7.jpg",
    file_path: "women/bottoms/jeans/jeans_7.jpg",
    price: 1461,
    rating: 3.62,
  },
  {
    id: 71,
    category: "jeans",
    product_name: "jeans_8.jpg",
    file_path: "women/bottoms/jeans/jeans_8.jpg",
    price: 973,
    rating: 3.7,
  },
  {
    id: 72,
    category: "jeans",
    product_name: "jeans_9.jpg",
    file_path: "women/bottoms/jeans/jeans_9.jpg",
    price: 560,
    rating: 4.24,
  },
  {
    id: 73,
    category: "pants",
    product_name: "pants_1.jpg",
    file_path: "women/bottoms/pants/pants_1.jpg",
    price: 563,
    rating: 3.48,
  },
  {
    id: 74,
    category: "pants",
    product_name: "pants_10.jpg",
    file_path: "women/bottoms/pants/pants_10.jpg",
    price: 1102,
    rating: 4.09,
  },
  {
    id: 75,
    category: "pants",
    product_name: "pants_11.jpg",
    file_path: "women/bottoms/pants/pants_11.jpg",
    price: 1644,
    rating: 4.58,
  },
  {
    id: 76,
    category: "pants",
    product_name: "pants_12.jpg",
    file_path: "women/bottoms/pants/pants_12.jpg",
    price: 796,
    rating: 4.78,
  },
  {
    id: 77,
    category: "pants",
    product_name: "pants_2.jpg",
    file_path: "women/bottoms/pants/pants_2.jpg",
    price: 698,
    rating: 4.36,
  },
  {
    id: 78,
    category: "pants",
    product_name: "pants_3.jpg",
    file_path: "women/bottoms/pants/pants_3.jpg",
    price: 1576,
    rating: 3.53,
  },
  {
    id: 79,
    category: "pants",
    product_name: "pants_4.jpg",
    file_path: "women/bottoms/pants/pants_4.jpg",
    price: 350,
    rating: 4.08,
  },
  {
    id: 80,
    category: "pants",
    product_name: "pants_5.jpg",
    file_path: "women/bottoms/pants/pants_5.jpg",
    price: 1916,
    rating: 3.8,
  },
  {
    id: 81,
    category: "pants",
    product_name: "pants_6.jpg",
    file_path: "women/bottoms/pants/pants_6.jpg",
    price: 507,
    rating: 3.37,
  },
  {
    id: 82,
    category: "pants",
    product_name: "pants_7.jpg",
    file_path: "women/bottoms/pants/pants_7.jpg",
    price: 650,
    rating: 4.5,
  },
  {
    id: 83,
    category: "pants",
    product_name: "pants_8.jpg",
    file_path: "women/bottoms/pants/pants_8.jpg",
    price: 1417,
    rating: 4.85,
  },
  {
    id: 84,
    category: "pants",
    product_name: "pants_9.jpg",
    file_path: "women/bottoms/pants/pants_9.jpg",
    price: 567,
    rating: 4.83,
  },
  {
    id: 85,
    category: "skirts",
    product_name: "skirts_1.jpg",
    file_path: "women/bottoms/skirts/skirts_1.jpg",
    price: 1365,
    rating: 4.03,
  },
  {
    id: 86,
    category: "skirts",
    product_name: "skirts_10.jpg",
    file_path: "women/bottoms/skirts/skirts_10.jpg",
    price: 1288,
    rating: 3.53,
  },
  {
    id: 87,
    category: "skirts",
    product_name: "skirts_11.jpg",
    file_path: "women/bottoms/skirts/skirts_11.jpg",
    price: 1740,
    rating: 3.49,
  },
  {
    id: 88,
    category: "skirts",
    product_name: "skirts_12.jpg",
    file_path: "women/bottoms/skirts/skirts_12.jpg",
    price: 870,
    rating: 3.67,
  },
  {
    id: 89,
    category: "skirts",
    product_name: "skirts_2.jpg",
    file_path: "women/bottoms/skirts/skirts_2.jpg",
    price: 1834,
    rating: 3.68,
  },
  {
    id: 90,
    category: "skirts",
    product_name: "skirts_3.jpg",
    file_path: "women/bottoms/skirts/skirts_3.jpg",
    price: 1084,
    rating: 4.44,
  },
  {
    id: 91,
    category: "skirts",
    product_name: "skirts_4.jpg",
    file_path: "women/bottoms/skirts/skirts_4.jpg",
    price: 638,
    rating: 4.34,
  },
  {
    id: 92,
    category: "skirts",
    product_name: "skirts_5.jpg",
    file_path: "women/bottoms/skirts/skirts_5.jpg",
    price: 1902,
    rating: 4.07,
  },
  {
    id: 93,
    category: "skirts",
    product_name: "skirts_6.jpg",
    file_path: "women/bottoms/skirts/skirts_6.jpg",
    price: 1486,
    rating: 3.14,
  },
  {
    id: 94,
    category: "skirts",
    product_name: "skirts_7.jpg",
    file_path: "women/bottoms/skirts/skirts_7.jpg",
    price: 956,
    rating: 3.81,
  },
  {
    id: 95,
    category: "skirts",
    product_name: "skirts_8.jpg",
    file_path: "women/bottoms/skirts/skirts_8.jpg",
    price: 1213,
    rating: 4.85,
  },
  {
    id: 96,
    category: "skirts",
    product_name: "skirts_9.jpg",
    file_path: "women/bottoms/skirts/skirts_9.jpg",
    price: 1470,
    rating: 4.59,
  },
  {
    id: 97,
    category: "casual dresses",
    product_name: "casual dresses_1.jpg",
    file_path: "women/dresses/casual dresses/casual dresses_1.jpg",
    price: 835,
    rating: 3.5,
  },
  {
    id: 98,
    category: "casual dresses",
    product_name: "casual dresses_10.jpg",
    file_path: "women/dresses/casual dresses/casual dresses_10.jpg",
    price: 428,
    rating: 4.91,
  },
  {
    id: 99,
    category: "casual dresses",
    product_name: "casual dresses_11.jpg",
    file_path: "women/dresses/casual dresses/casual dresses_11.jpg",
    price: 1326,
    rating: 4.2,
  },
  {
    id: 100,
    category: "casual dresses",
    product_name: "casual dresses_12.jpg",
    file_path: "women/dresses/casual dresses/casual dresses_12.jpg",
    price: 1909,
    rating: 3.94,
  },
  {
    id: 101,
    category: "casual dresses",
    product_name: "casual dresses_2.jpg",
    file_path: "women/dresses/casual dresses/casual dresses_2.jpg",
    price: 449,
    rating: 3.02,
  },
  {
    id: 102,
    category: "casual dresses",
    product_name: "casual dresses_3.jpg",
    file_path: "women/dresses/casual dresses/casual dresses_3.jpg",
    price: 1131,
    rating: 4.66,
  },
  {
    id: 103,
    category: "casual dresses",
    product_name: "casual dresses_4.jpg",
    file_path: "women/dresses/casual dresses/casual dresses_4.jpg",
    price: 1748,
    rating: 3.86,
  },
  {
    id: 104,
    category: "casual dresses",
    product_name: "casual dresses_5.jpg",
    file_path: "women/dresses/casual dresses/casual dresses_5.jpg",
    price: 684,
    rating: 3.39,
  },
  {
    id: 105,
    category: "casual dresses",
    product_name: "casual dresses_6.jpg",
    file_path: "women/dresses/casual dresses/casual dresses_6.jpg",
    price: 899,
    rating: 4.72,
  },
  {
    id: 106,
    category: "casual dresses",
    product_name: "casual dresses_7.jpg",
    file_path: "women/dresses/casual dresses/casual dresses_7.jpg",
    price: 304,
    rating: 3.04,
  },
  {
    id: 107,
    category: "casual dresses",
    product_name: "casual dresses_8.jpg",
    file_path: "women/dresses/casual dresses/casual dresses_8.jpg",
    price: 1987,
    rating: 3.69,
  },
  {
    id: 108,
    category: "casual dresses",
    product_name: "casual dresses_9.jpg",
    file_path: "women/dresses/casual dresses/casual dresses_9.jpg",
    price: 317,
    rating: 3.11,
  },
  {
    id: 109,
    category: "formal dresses",
    product_name: "formal dresses_1.jpg",
    file_path: "women/dresses/formal dresses/formal dresses_1.jpg",
    price: 1316,
    rating: 4.63,
  },
  {
    id: 110,
    category: "formal dresses",
    product_name: "formal dresses_10.jpg",
    file_path: "women/dresses/formal dresses/formal dresses_10.jpg",
    price: 1850,
    rating: 3.6,
  },
  {
    id: 111,
    category: "formal dresses",
    product_name: "formal dresses_11.jpg",
    file_path: "women/dresses/formal dresses/formal dresses_11.jpg",
    price: 1621,
    rating: 4.46,
  },
  {
    id: 112,
    category: "formal dresses",
    product_name: "formal dresses_12.jpg",
    file_path: "women/dresses/formal dresses/formal dresses_12.jpg",
    price: 308,
    rating: 3.73,
  },
  {
    id: 113,
    category: "formal dresses",
    product_name: "formal dresses_2.jpg",
    file_path: "women/dresses/formal dresses/formal dresses_2.jpg",
    price: 929,
    rating: 4.56,
  },
  {
    id: 114,
    category: "formal dresses",
    product_name: "formal dresses_3.jpg",
    file_path: "women/dresses/formal dresses/formal dresses_3.jpg",
    price: 1680,
    rating: 4.86,
  },
  {
    id: 115,
    category: "formal dresses",
    product_name: "formal dresses_4.jpg",
    file_path: "women/dresses/formal dresses/formal dresses_4.jpg",
    price: 1527,
    rating: 3.56,
  },
  {
    id: 116,
    category: "formal dresses",
    product_name: "formal dresses_5.jpg",
    file_path: "women/dresses/formal dresses/formal dresses_5.jpg",
    price: 1599,
    rating: 4.52,
  },
  {
    id: 117,
    category: "formal dresses",
    product_name: "formal dresses_6.jpg",
    file_path: "women/dresses/formal dresses/formal dresses_6.jpg",
    price: 856,
    rating: 4.24,
  },
  {
    id: 118,
    category: "formal dresses",
    product_name: "formal dresses_7.jpg",
    file_path: "women/dresses/formal dresses/formal dresses_7.jpg",
    price: 486,
    rating: 4.65,
  },
  {
    id: 119,
    category: "formal dresses",
    product_name: "formal dresses_8.jpg",
    file_path: "women/dresses/formal dresses/formal dresses_8.jpg",
    price: 1256,
    rating: 4.79,
  },
  {
    id: 120,
    category: "formal dresses",
    product_name: "formal dresses_9.jpg",
    file_path: "women/dresses/formal dresses/formal dresses_9.jpg",
    price: 1501,
    rating: 3.97,
  },
  {
    id: 121,
    category: "traditional dresses",
    product_name: "traditional dresses_1.jpg",
    file_path: "women/dresses/traditional dresses/traditional dresses_1.jpg",
    price: 614,
    rating: 3.2,
  },
  {
    id: 122,
    category: "traditional dresses",
    product_name: "traditional dresses_10.jpg",
    file_path: "women/dresses/traditional dresses/traditional dresses_10.jpg",
    price: 1672,
    rating: 3.69,
  },
  {
    id: 123,
    category: "traditional dresses",
    product_name: "traditional dresses_11.jpg",
    file_path: "women/dresses/traditional dresses/traditional dresses_11.jpg",
    price: 491,
    rating: 3.89,
  },
  {
    id: 124,
    category: "traditional dresses",
    product_name: "traditional dresses_12.jpg",
    file_path: "women/dresses/traditional dresses/traditional dresses_12.jpg",
    price: 378,
    rating: 4.78,
  },
  {
    id: 125,
    category: "traditional dresses",
    product_name: "traditional dresses_2.jpg",
    file_path: "women/dresses/traditional dresses/traditional dresses_2.jpg",
    price: 990,
    rating: 4.53,
  },
  {
    id: 126,
    category: "traditional dresses",
    product_name: "traditional dresses_3.jpg",
    file_path: "women/dresses/traditional dresses/traditional dresses_3.jpg",
    price: 1069,
    rating: 3.45,
  },
  {
    id: 127,
    category: "traditional dresses",
    product_name: "traditional dresses_4.jpg",
    file_path: "women/dresses/traditional dresses/traditional dresses_4.jpg",
    price: 1135,
    rating: 3.98,
  },
  {
    id: 128,
    category: "traditional dresses",
    product_name: "traditional dresses_5.jpg",
    file_path: "women/dresses/traditional dresses/traditional dresses_5.jpg",
    price: 533,
    rating: 4.77,
  },
  {
    id: 129,
    category: "traditional dresses",
    product_name: "traditional dresses_6.jpg",
    file_path: "women/dresses/traditional dresses/traditional dresses_6.jpg",
    price: 793,
    rating: 4.92,
  },
  {
    id: 130,
    category: "traditional dresses",
    product_name: "traditional dresses_7.jpg",
    file_path: "women/dresses/traditional dresses/traditional dresses_7.jpg",
    price: 1715,
    rating: 4.84,
  },
  {
    id: 131,
    category: "traditional dresses",
    product_name: "traditional dresses_8.jpg",
    file_path: "women/dresses/traditional dresses/traditional dresses_8.jpg",
    price: 469,
    rating: 4.25,
  },
  {
    id: 132,
    category: "traditional dresses",
    product_name: "traditional dresses_9.jpg",
    file_path: "women/dresses/traditional dresses/traditional dresses_9.jpg",
    price: 1011,
    rating: 4.87,
  },
  {
    id: 133,
    category: "casual tops",
    product_name: "casual tops_1.jpg",
    file_path: "women/tops/casual tops/casual tops_1.jpg",
    price: 1129,
    rating: 4.76,
  },
  {
    id: 134,
    category: "casual tops",
    product_name: "casual tops_10.jpg",
    file_path: "women/tops/casual tops/casual tops_10.jpg",
    price: 1155,
    rating: 4.78,
  },
  {
    id: 135,
    category: "casual tops",
    product_name: "casual tops_11.jpg",
    file_path: "women/tops/casual tops/casual tops_11.jpg",
    price: 678,
    rating: 4.85,
  },
  {
    id: 136,
    category: "casual tops",
    product_name: "casual tops_12.jpg",
    file_path: "women/tops/casual tops/casual tops_12.jpg",
    price: 1436,
    rating: 3.99,
  },
  {
    id: 137,
    category: "casual tops",
    product_name: "casual tops_2.jpg",
    file_path: "women/tops/casual tops/casual tops_2.jpg",
    price: 641,
    rating: 4.42,
  },
  {
    id: 138,
    category: "casual tops",
    product_name: "casual tops_3.jpg",
    file_path: "women/tops/casual tops/casual tops_3.jpg",
    price: 941,
    rating: 3.5,
  },
  {
    id: 139,
    category: "casual tops",
    product_name: "casual tops_4.jpg",
    file_path: "women/tops/casual tops/casual tops_4.jpg",
    price: 1108,
    rating: 4.52,
  },
  {
    id: 140,
    category: "casual tops",
    product_name: "casual tops_5.jpg",
    file_path: "women/tops/casual tops/casual tops_5.jpg",
    price: 432,
    rating: 3.47,
  },
  {
    id: 141,
    category: "casual tops",
    product_name: "casual tops_6.jpg",
    file_path: "women/tops/casual tops/casual tops_6.jpg",
    price: 508,
    rating: 3.23,
  },
  {
    id: 142,
    category: "casual tops",
    product_name: "casual tops_7.jpg",
    file_path: "women/tops/casual tops/casual tops_7.jpg",
    price: 1948,
    rating: 4.63,
  },
  {
    id: 143,
    category: "casual tops",
    product_name: "casual tops_8.jpg",
    file_path: "women/tops/casual tops/casual tops_8.jpg",
    price: 616,
    rating: 3.93,
  },
  {
    id: 144,
    category: "casual tops",
    product_name: "casual tops_9.jpg",
    file_path: "women/tops/casual tops/casual tops_9.jpg",
    price: 1466,
    rating: 3.42,
  },
  {
    id: 145,
    category: "formal tops",
    product_name: "formal tops_1.jpg",
    file_path: "women/tops/formal tops/formal tops_1.jpg",
    price: 492,
    rating: 3.94,
  },
  {
    id: 146,
    category: "formal tops",
    product_name: "formal tops_10.jpg",
    file_path: "women/tops/formal tops/formal tops_10.jpg",
    price: 921,
    rating: 4.18,
  },
  {
    id: 147,
    category: "formal tops",
    product_name: "formal tops_11.jpg",
    file_path: "women/tops/formal tops/formal tops_11.jpg",
    price: 1882,
    rating: 4.69,
  },
  {
    id: 148,
    category: "formal tops",
    product_name: "formal tops_12.jpg",
    file_path: "women/tops/formal tops/formal tops_12.jpg",
    price: 981,
    rating: 4.9,
  },
  {
    id: 149,
    category: "formal tops",
    product_name: "formal tops_2.jpg",
    file_path: "women/tops/formal tops/formal tops_2.jpg",
    price: 306,
    rating: 4.09,
  },
  {
    id: 150,
    category: "formal tops",
    product_name: "formal tops_3.jpg",
    file_path: "women/tops/formal tops/formal tops_3.jpg",
    price: 1694,
    rating: 4.12,
  },
  {
    id: 151,
    category: "formal tops",
    product_name: "formal tops_4.jpg",
    file_path: "women/tops/formal tops/formal tops_4.jpg",
    price: 1690,
    rating: 3.24,
  },
  {
    id: 152,
    category: "formal tops",
    product_name: "formal tops_5.jpg",
    file_path: "women/tops/formal tops/formal tops_5.jpg",
    price: 1081,
    rating: 3.27,
  },
  {
    id: 153,
    category: "formal tops",
    product_name: "formal tops_6.jpg",
    file_path: "women/tops/formal tops/formal tops_6.jpg",
    price: 529,
    rating: 4.57,
  },
  {
    id: 154,
    category: "formal tops",
    product_name: "formal tops_7.jpg",
    file_path: "women/tops/formal tops/formal tops_7.jpg",
    price: 1331,
    rating: 4.06,
  },
  {
    id: 155,
    category: "formal tops",
    product_name: "formal tops_8.jpg",
    file_path: "women/tops/formal tops/formal tops_8.jpg",
    price: 1779,
    rating: 3.21,
  },
  {
    id: 156,
    category: "formal tops",
    product_name: "formal tops_9.jpg",
    file_path: "women/tops/formal tops/formal tops_9.jpg",
    price: 1208,
    rating: 4.69,
  },
  {
    id: 157,
    category: "traditional tops",
    product_name: "traditional tops_1.jpg",
    file_path: "women/tops/traditional tops/traditional tops_1.jpg",
    price: 454,
    rating: 3.49,
  },
  {
    id: 158,
    category: "traditional tops",
    product_name: "traditional tops_10.jpg",
    file_path: "women/tops/traditional tops/traditional tops_10.jpg",
    price: 381,
    rating: 4.01,
  },
  {
    id: 159,
    category: "traditional tops",
    product_name: "traditional tops_11.jpg",
    file_path: "women/tops/traditional tops/traditional tops_11.jpg",
    price: 1417,
    rating: 3.66,
  },
  {
    id: 160,
    category: "traditional tops",
    product_name: "traditional tops_12.jpg",
    file_path: "women/tops/traditional tops/traditional tops_12.jpg",
    price: 807,
    rating: 3.17,
  },
  {
    id: 161,
    category: "traditional tops",
    product_name: "traditional tops_2.jpg",
    file_path: "women/tops/traditional tops/traditional tops_2.jpg",
    price: 764,
    rating: 4.39,
  },
  {
    id: 162,
    category: "traditional tops",
    product_name: "traditional tops_3.jpg",
    file_path: "women/tops/traditional tops/traditional tops_3.jpg",
    price: 1942,
    rating: 4.45,
  },
  {
    id: 163,
    category: "traditional tops",
    product_name: "traditional tops_4.jpg",
    file_path: "women/tops/traditional tops/traditional tops_4.jpg",
    price: 389,
    rating: 3.55,
  },
  {
    id: 164,
    category: "traditional tops",
    product_name: "traditional tops_5.jpg",
    file_path: "women/tops/traditional tops/traditional tops_5.jpg",
    price: 1887,
    rating: 4.7,
  },
  {
    id: 165,
    category: "traditional tops",
    product_name: "traditional tops_6.jpg",
    file_path: "women/tops/traditional tops/traditional tops_6.jpg",
    price: 638,
    rating: 3.66,
  },
  {
    id: 166,
    category: "traditional tops",
    product_name: "traditional tops_7.jpg",
    file_path: "women/tops/traditional tops/traditional tops_7.jpg",
    price: 1071,
    rating: 3.92,
  },
  {
    id: 167,
    category: "traditional tops",
    product_name: "traditional tops_8.jpg",
    file_path: "women/tops/traditional tops/traditional tops_8.jpg",
    price: 1900,
    rating: 4.26,
  },
  {
    id: 168,
    category: "traditional tops",
    product_name: "traditional tops_9.jpg",
    file_path: "women/tops/traditional tops/traditional tops_9.jpg",
    price: 640,
    rating: 3.51,
  },
];
